name: FTP Deployment for Rentplan App

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy-rentplan:
    environment: "plesk-rentplan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Setup PHP 8.2 Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer Dependencies
        run: composer install

      - name: Setup Node.js 20 Environment
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 🚀 Build the Portal Frontend for https://app.rentplan.nl
      - name: Build Portal Frontend for Rentplan App
        run: |
          cd frontend
          npm install
          npm run build -- --mode production
          cd ..

      # 🚀 Deploy the built Portal Frontend to https://app.rentplan.nl via FTP
      - name: FTP Deploy Portal Frontend to https://app.rentplan.nl
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: rentplan.nl
          username: rentplan-app-ftp
          password: 39fq@a28I
          local-dir: ./
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            fileToExclude.txt
        continue-on-error: true
